name: build

on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Install Nodejs LTS
        uses: actions/setup-node@v5
        with:
          node-version: lts/*

      - name: Download font package
        shell: bash
        run: |
          make webfonts

      - name: Build Site
        shell: bash
        run: |
          yarn install --immutable
          GIT_SHA=$(git rev-parse HEAD) yarn build

      - name: Upload artifact for deployment
        uses: actions/upload-artifact@v4
        with:
          name: release
          path: build/
